# Generated by Django 4.1.4 on 2023-01-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servingse_unit',
            new_name='servings_unit',
        ),
    ]
